<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://claim.carinsurance.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://claim.carinsurance.com" xmlns:intf="http://claim.carinsurance.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://claim.carinsurance.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="testConnection">
    <complexType/>
   </element>
   <element name="testConnectionResponse">
    <complexType>
     <sequence>
      <element name="testConnectionReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="testConnectionResponse">

      <wsdl:part element="impl:testConnectionResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="testConnectionRequest">

      <wsdl:part element="impl:testConnection" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="DBConnection">

      <wsdl:operation name="testConnection">

         <wsdl:input message="impl:testConnectionRequest" name="testConnectionRequest">

       </wsdl:input>

         <wsdl:output message="impl:testConnectionResponse" name="testConnectionResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="DBConnectionSoapBinding" type="impl:DBConnection">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="testConnection">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="testConnectionRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="testConnectionResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="DBConnectionService">

      <wsdl:port binding="impl:DBConnectionSoapBinding" name="DBConnection">

         <wsdlsoap:address location="http://localhost:8080/CarInsurance/services/DBConnection"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
